gloddy-dev/gloddy-client

app/globals.css, app/layout.tsx, style/theme/colors.ts
- layout 및 global css 설정
layout 및 global css 설정하였습니다.
```js
* {
font-size: 3.7vw;
}
@media (min-width: 420px) {
* {
font-size: 16px;
}
}
```
420px기준으로, 420px이상이라면 420px넘어서는 여백이 보이고, 420px이하라면 사이즈가 줄어들수록 최상단 글씨 크기 또한 줄어듭니다 -> 하위 요소들을 rem을 크기 단위로 설정하면 그 또한 크기가 줄어듭니다.
기존 피그마의 px단위는 `px to rem`확장 프로그램을 이용하여 rem단위로 변환하여 사용하면 됩니다.
16px = 1rem기준입니다.
=> layout 및 global.css 설정

app/layout.tsx, components/TextField/AuthInput.tsx
- 신규피쳐
- 회원가입에서 사용하는 TextField 컴포넌트를 제작하였습니다.
- 추후에 게시판 등 TextField의 확장성을 고려해여 Input 폴더 > AuthInput.tsx로 만들었습니다.
=> AuthInput 공통 컴포넌트

components/common/NavigationBar/TopNavigationBar.tsx, public/assets/arrow_back.svg
- 신규피처
1. Top NavigationBar를 구현하였습니다.
- props : text(가운데 메시지), right(오른쪽에 올 요소)
추후에 앱 내 웹뷰로 확장하게 될 때 Top NavigationBar를 Safe Area 상단에 넣어도 좋을 것 같습니다
=> Top Navigation Bar 구현

.github/labeler.yml, .github/workflows/pr-labeler.yml
- 신규 피처
1. PR 및 Issue의 제목에 따라 label 자동부여하는 Github action입니다.
- Github action이 자꾸 실패하는데, Merge 후 한번 더 시도해보겠습니다.
=> Test : Label 자동 부여 Github Action

.github/workflows/auto-publishing.yml, build.sh
- 신규 피처
1. 테스트 및 보완 PR 입니다.
- 이전 [Repository](https://github.com/gloddy-dev/gloddy-client/pull/65)를 참고해주세요
=> 🔬 Test : 자동 배포 Github Action 테스트

.github/workflows/auto-publishing.yml, build.sh
- 이슈대응
1. Github Action 발생하는 조건을
```
on:
push:
branches:
- 'develop'
```
로 수정하였습니다.
2. output repository를 team repository명인 `gloddy-client`로 수정하였습니다.
=> 🐛 Fix : 모든 branch에서 배포 Github Action 일어나는 에러 해결

.github/workflows/auto-publishing.yml, app/join/step4/page.tsx
- 이슈대응
1. 기존 Team Repository의 모든 파일이 복사되지 않는 현상이 발생했습니다. 그래서, source-directory가 문제인지 싶어 기존 'output'에서 '.'로 수정하였습니다.
=> 🚿 Refactoring : repository의 모든 내용 복사

components/common/Tabs/index.tsx, hooks/useFunnel.tsx
- close #136
1. 특정 탭에서 다른 페이지로 이동후 다시 뒤로 돌아갔을 때 정상적으로 돌아가지 않는 문제를 해결했습니다.
2. 추가로 useFunnel에서도 history API를 사용해서 push, replace하지 않고, useRouter를 사용하도록 변경했습니다.
=> Fix : Tabs 컴포넌트 라우팅 이슈 해결

app/join/funnels/step4/components/BirthdaySection.client.tsx, app/join/funnels/step5/components/InputForm.client.tsx, components/common/SwipePicker/DateSwipePicker.tsx, components/common/SwipePicker/SwipePicker.tsx, constants/personalityList.ts, types/index.ts
- 리팩토링
1. 기존 Swiper Picker는 불필요한 props가 많았습니다.
- 기존 props
```js
selectList: string[];
keyType?: string;
isTimeZone?: boolean;
isRangeString?: boolean;
isFirst?: boolean;
isLast?: boolean;
setValue?: (value: string | GenderType, keyType: string) => void;
value?: string | GenderType;
}
```
- 수정 후 props
```js
selectList: string[] | number[];
setValue: (value: string | number | GenderType) => void;
isFirst?: boolean;
isLast?: boolean;
```
- `Swiper Picker`컴포넌트에 필요하다고 생각되는 props만 남겨두었습니다.
- 기존에 `DatePicker`를 위해 추가되었던 keyType은, `SwiperPIcker`의 역할이 아니라고 생각하여 제거하였습니다. 이는 `SwiperPicker`에 props로 내려주기 전에 각 함수에서 year/month/date에 따라 처리해주는 것이 올바른 로직이라 생각하였습니다.
- `TimeSwipePicker`에서만 쓰이는 `isTimeZone`과 `isRangeString`또한 `SwiperPIcker`의 역할이 아니고, 새로운 컴포넌트로 만드는 것이 적합하다고 생각하여 제거하였습니다.
- 어제 회의에서 디자이너분이 가운데 …
=> Refactoring : Swiper Picker 리팩토링

app/join/funnels/step1/components/NumberVerifyForm.client.tsx, app/join/funnels/step1/util.ts
- 리팩토링
#145 
1. login api를 쏠 때의 payload의 형식이 달라서 없는 유저라고 응답이 왔습니다. 이에 따라 payload 형식을 바꿔주는 함수 `formatWithoutSpace`를 추가했습니다.
2. `formatWithoutSpace`와 `formatWithoutHyphen` util함수를 분리하여 코드를 좀 더 직관적으로 하였습니다.
토큰 설정은 아직 하지 않았습니다.
로그인 > 토큰 설정을 하게되는데, 이 토큰 관리를 어떻게 해야 할 지 더 논의 및 고민을 해봐야할 것 같습니다.
=> Refactoring : login api 포맷 설정

apis/groups/type.ts, app/grouping/components/GroupingCardList.client.tsx, app/grouping/create/components/inputSection/SubmitSection.tsx, app/grouping/create/type.ts, app/grouping/page.tsx, app/join/funnels/step5/components/InputForm.client.tsx, components/common/SwipePicker/TimeSwipePicker.tsx, constants/dummyData.ts, types/index.ts
- 신규 피처
1. dummy data는 dummyData.ts로 코드 분리하였습니다.
2. 고도/위도 타입을 서버 측 api에 맞게 string으로 수정하였습니다.
3. 기존 hour/minute을 number로 관리하여 매 번 formatting해줘야 하는 번거로움이 있었습니다. 이에 따라 string으로 수정하였습니다.
=> Featuring : create-group, grouping api 구현

app/grouping/[id]/components/detail/LocationSection.server.tsx
- 신규 피처
1. 카카오맵 SDK를 이용용하여 지도를 띄었습니다.
=> Featuring : 지도 API 구현

apis/config/publicApi.ts, app/join/funnels/step1/components/NumberVerifyForm.client.tsx, app/join/funnels/step3/components/CertificationForm.client.tsx, app/join/funnels/step3/type.ts, app/join/funnels/step4/components/InputForm.client.tsx, app/join/funnels/step4/components/NicknameSection.client.tsx, app/join/funnels/step5/components/InputForm.client.tsx, app/join/funnels/step5/components/PersonalityItem.server.tsx, app/join/type.ts, components/common/Input/Input.tsx, components/common/SwipePicker/DateSwipePicker.tsx, components/common/SwipePicker/GenderSwipePicker.tsx, constants/regexr.ts
- 신규 피처
1. 휴대전화 번호 인증
2. 닉네임 유효하지 않을 경우
1. certificate -> verify로 네이밍 통일화
2. getValues -> watch로 수정함으로써 `input`의 변화를 subscribe하여 실시간 반영
3. `<Input>` 공통 컴포넌트에 `errorMessage`를 추가하였습니다.
4. Birthday year 범위를 기획에 맞게 1980 ~ 2010으로 수정하였습니다.
=> Refactoring : 회원가입 페이지 에러 핸들링

.github/workflows/auto-milestones.yml, .github/workflows/auto-publishing-develop.yml, .github/workflows/auto-publishing-feature.yml, app/grouping/create/components/CreateGroupContext.tsx, app/grouping/create/components/inputSection/ImageSection.client.tsx, app/grouping/create/type.ts, build.sh
- 신규 피처
1. 다른 branch로 복사하여 배포하는 github action에서 불필요한 과정을 제거하였습니다.
1. `build.sh` 실행 : output폴더에 복사하는 과정 제거
2. ruby와 mustache 설치
=> Refactoring : GitHub action 리팩토링

constants/dummyData.ts
=> Fix : 빠진 괄호 추가

.github/workflows/ci.yml, jest.config.js
- 리팩토링
- close #200 
1. 테스트 범위를 수정하였습니다.
- jest의 test범위는 모든 범위에서 utils폴더 내의 파일들입니다.
- codecov의 coverage 적용 범위는 src/utils안에 있는 모든 util함수입니다.
=> Setting : test 범위 수정

src/components/Button/Button.tsx, src/components/Button/ButtonGroup.tsx, src/components/Button/FloatAddButton.tsx, src/components/Button/IconButton.tsx, src/components/Button/index.ts, src/components/Divider/Divider.tsx, src/components/Divider/index.ts
- 신규 피처
- close #189
- close #192
1. Divider 컴포넌트를 구현했습니다.
flex 내부에서 사용할 때는 flexItem prop을 추가해야 합니다.
```tsx
<Divider direction="vertical" thickness="thick" flexItem />
```
2. Divider 및 Button 컴포넌트를 polymorphic하게 변경했습니다.
특히 Button 컴포넌트는 a 태그로 바꾸어 사용할 일이 많을 것 같아 바꾸게 되었습니다.
```tsx
<Button as="a" href="/">링크<Button>
```
=> feat: Divider 컴포넌트 구현 및 Button 컴포넌트 polymorphic 하게 변경

src/components/Tag/Tag.tsx, src/components/Tag/index.ts
- 신규 피처
- close #205
1. Tag 컴포넌트를 구현했습니다.
```tsx
const [selectedTagIds, setSelectedTagIds] = useState<number[]>([]);
const tagList = [
{ id: 1, text: '🎉 외향적인' },
{ id: 2, text: '🏠 내향적인' },
{ id: 3, text: '🧐 신중한' },
];
const handleSelectedClick = useCallback(
(id: number) =>
setSelectedTagIds((prev) => {
if (prev.includes(id)) {
return prev.filter((prevId) => prevId !== id);
}
return [...prev, id];
}),
[]
);
return (
<>
{tagList.map((tag) => (
<Tag
key={tag.id}
id={tag.id}
isSelected={selectedTagIds.includes(tag.id)}
onSelected={handleSelectedClick}
>
{tag.text}
</Tag>
))}
</>
);
}
=> Feature : Tag 컴포넌트 구현

src/components/Button/Button.tsx, src/components/Button/ButtonGroup.tsx
- 신규 피처
- close #207
1. Button fullWidth prop 추가
2. ButtonGroup isSpacing 추가
=> Feature : Button fullWidth prop 추가 및 ButtonGroup isSpacing 추가

src/components/Layout/Flex.tsx
- 신규 피처
1. Flex에서 `flex`속성이 적용안되던 에러를 해결하였습니다.
=> Fix : Flex 공통 컴포넌트 에러 해결

src/components/TextField/TextField.client.tsx
- 신규 피처
1. TextField - Spacing label여부에 따라 on/off되도록 수정하였습니다.
=> Refactoring : TextField - Spacing label여부에 따라 on/off

.github/ISSUE_TEMPLATE/Feature.md, .github/ISSUE_TEMPLATE/Refactoring.md, .github/ISSUE_TEMPLATE/TroubleShooting.md
- 신규 피처
1. Issue Template - Refactoring을 추가하고, 네이밍을 통일했습니다.
=> Refactoring : issue template 교체

src/app/(main)/grouping/components/GroupingCardList.client.tsx, src/app/(main)/grouping/util.ts, src/components/Card/GroupingCard.client.tsx, src/components/Tabs/Tabs.client.tsx
- 이슈대응
- close #240 
1. 나의 모임 페이지 > Tabs에서 발생하는 에러를 해결하였습니다.
2. 그루핑 페이지 날짜 format을 수정하였습니다.
=> Fix : 그루핑, 나의 모임 페이지 오류 수정

src/apis/auth/mutations.ts, src/app/(sub)/join/funnels/step3/components/EmailForm.client.tsx, src/app/(sub)/join/funnels/step5/components/InputForm.client.tsx, src/components/SegmentGroup/SegmentGroup.client.tsx, src/constants/dummyData.ts
- 신규 피처
- close #245 
1. 회원가입 중 발생한 에러를 수정하였습니다.
2. 회원가입 onSuccess 로직을 mutation으로 분리하였습니다.
=> Refactoring : 회원가입 중 에러 수정 및 리팩토링

src/app/(main)/profile/setting/components/LinkSection.server.tsx, src/app/(main)/profile/setting/components/ProfileSection.client.tsx, src/app/(main)/profile/setting/components/SettingHeader.tsx, src/app/(main)/profile/setting/page.tsx
- 신규 피처
- close #253 
1. 프로필 > 환경설정 페이지를 구현했습니다.
=> Page : 환경 설정 페이지 구현

src/app/(sub)/join/funnels/step2/components/SchoolForm.client.tsx, src/constants/regexr.ts
- 신규 피처
- close #288 
1. step2의 학교 입력에서 버튼이 정상적으로 동작하지 않는 이슈가 있었습니다. react-hook-form의 `formState`,`getfFormState`으로 isValid상태를 분기처리해주었었는데, setValue로 값을 바꾸어주는 과정 때문에 정상적으로 동작하지 않았습니다. 이에 따라 정규표현식과 직접 비교하는 식으로 로직을 수정하였습니다.
=> fix : 학교 입력 이슈 해결

src/components/Tabs/Tabs.client.tsx
- 신규 피처
- close #290 
1. `Tab`에 disabled조건을 추가하였습니다.
```js
<Tabs.Tab value="articles" text="게시판" disabled />
```
=> Feature : tabs - disabled 조건 추가

src/app/globals.css, src/components/TextField/TextField.client.tsx
- 신규 피처
- close #297 
1. textarea의 scrollbar를 구현하였습니다. 현재, input이 아닌 바깥 section에서 padding값을 설정하여서 scrollbar가 피그마처럼은 구현은 되지 않았지만 손을 보면 사이드 이펙트가 발생할 것을 고려해 건들지 않았습니다. QA 이후 리팩토링 때 수정하도록하겠습니다.
=> Feature : textarea scrollbar 구현

src/app/(sub)/join/funnels/step1/components/FormSection.client.tsx, src/app/(sub)/join/funnels/step1/components/NumberForm.client.tsx, src/app/(sub)/join/funnels/step1/components/NumberVerifyForm.client.tsx, src/components/Provider/TimerProvider.client.tsx, src/components/Provider/index.ts
- 신규 피처
- close #292 
1. TimerProvider를 공통 컴포넌트로 뺐습니다. 이제 timer를 여러 컴포넌트에서 props drilling없이 사용하고 싶다면 `TimerProvider`를 사용하면 됩니다.
=> Feature : 회원가입 - 휴대폰 인증 페이지 timer 구현

src/apis/groups/apis.ts, src/apis/groups/type.ts, src/app/(main)/grouping/[groupId]/components/GroupingDetail.client.tsx, src/app/(main)/grouping/[groupId]/components/TopSection.client.tsx, src/app/(main)/grouping/[groupId]/components/detail/LocationSection.client.tsx, src/app/(main)/grouping/[groupId]/manage/components/ApplyCard.client.tsx, src/app/(main)/grouping/[groupId]/manage/components/ManageDetail.client.tsx, src/app/(main)/grouping/create/components/InputForm.client.tsx, src/app/(main)/grouping/util.ts, src/components/Card/GroupingCard.client.tsx, src/constants/dummyData.ts, src/utils/copyToClipboard.ts
- 신규 피처
1. 변경된 api에 맞게 타입을 변경했습니다.
2. 참여하고 있는 그룹이 아니면 게시판 탭을 disabled하게 했습니다.
올바르지 않은 방법으로 게시판 탭에 들어갔을 때 처리도 필요할 것 같습니다.
=> Refactoring : group, apply 타입 변경

src/app/(sub)/token/Token.tsx, src/app/(sub)/token/page.tsx, src/app/page.tsx, src/components/Card/GroupingCard.client.tsx, src/middleware.ts, src/utils/auth/tokenController.ts, src/utils/cookieController.ts
- 신규 피처
1. 루트 페이지 이동 후 토큰 여부에 따라 redirect하였습니다.
=> Feature : 토큰 여부에 따라 redirect

src/constants/dummyData.ts
=> Fix : 빌드 에러 수정

src/components/Card/GroupingCard.client.tsx, src/components/Footer/Footer.tsx
- 이슈대응
- close #316 
1. footer의 url 수정
2. GroupingCard 인원 수 변경
=> Fix : QA 2차 반영

src/app/(main)/profile/components/ProfileSection.client.tsx, src/app/(main)/profile/mates/components/MatesDetail.client.tsx, src/app/(sub)/join/funnels/step1/components/NumberVerifyForm.client.tsx, src/components/Card/GroupingCard.client.tsx
- 신규 피처
- close #336 
1. QA사항들을 반영하였습니다.
- 이미지 깨짐 현상
- 인증번호 재전송 로직 수정
- 타이멍 종료시 인증 번호 재요청 메시지 수정
=> Fix : QA 4차 반영

src/app/(main)/grouping/create/components/CreateGroupContext.tsx, src/app/(main)/grouping/create/components/CreateModal.client.tsx, src/app/(main)/grouping/create/components/LocationBottomSheet.client.tsx, src/app/(main)/grouping/create/components/LoctationItem.client.tsx, src/app/(main)/grouping/create/funnels/main/MainStep.client.tsx, src/app/(main)/grouping/create/funnels/main/SettingSection.client.tsx, src/app/(main)/grouping/create/type.ts, src/app/globals.css, src/components/Footer/Footer.tsx, src/components/Header/Header.tsx, src/components/Modal/Modal.client.tsx
- 신규 피처
- close #343
1.모임 개설 페이지의 위치 바텀시트 추가 및 입력 필드 모두 작성 시 눌리도록 변경했습니다.
=> Refactoring : 모임 개설 페이지의 위치 바텀시트 추가 및 입력 필드 모두 작성 시 눌리도록 변경

.github/workflows/ci.yml, .github/workflows/codeql.yml
- 신규 피처
- close #304 
1. `ci.yml`의 들여쓰기가 원인인 것 같아 수정했습니다.
=> Fix : CI 이슈 해결

src/components/Modal/Modal.client.tsx, src/components/Modal/Toast.client.tsx, src/hooks/useModal/ModalProvider.tsx, src/hooks/useModal/useModal.tsx
- 이슈대응
- close #355 
- close #353 
1. Modal 이슈를 해결하였습니다.
1. Modal창이 팍 꺼지는 이슈
2. 다른 페이지 이동 시 Modal 꺼지는 이슈
2. id이슈는 아직 해결하지 못하였습니다. 에러 메시지만 뜨고 실제로 에러상황은 발생하지 않아, 추후에 조금 더 고민해본 후 해결하겠습니다.
=> Fix : Modal issue 해결

src/apis/groups/apis.ts, src/apis/groups/mutations.tsx, src/apis/groups/queries.ts, src/apis/groups/type.ts, src/app/(main)/grouping/[groupId]/apply/components/InputForm.client.tsx, src/app/(main)/grouping/[groupId]/articles/[articleId]/components/ArticleHeader.client.tsx, src/app/(main)/grouping/[groupId]/articles/[articleId]/components/CommentForm.tsx, src/app/(main)/grouping/[groupId]/articles/[articleId]/components/CommentList.client.tsx, src/app/(main)/grouping/[groupId]/components/GroupDetailHeader.client.tsx, src/app/(main)/grouping/[groupId]/components/TopSection.client.tsx, src/app/(main)/grouping/[groupId]/components/articles/NoticeItem.client.tsx, src/app/(main)/grouping/[groupId]/components/articles/NoticeSection.client.tsx, src/app/(main)/grouping/[groupId]/manage/components/ApplyCard.client.tsx, src/app/(main)/grouping/[groupId]/manage/components/ManageHeader.client.tsx, src/app/(main)/grouping/[groupId]/write/components/InputForm.client.tsx, src/app/(main)/grouping/components/ArticleItem.client.tsx, src/app/(main)/grouping/components/WarningModal.client.tsx, src/app/(main)/grouping/create/funnels/main/MainStep.client.tsx, src/app/(main)/grouping/hooks/useMoreSheet.tsx, src/components/Card/CardHeader.client.tsx, src/components/Card/index.ts, src/components/Modal/BottomSheet.client.tsx, src/components/Modal/MoreBottomSheet.client.tsx, src/components/Modal/index.ts, src/components/common/SwipePicker/NumberSwipePicker.tsx
- 신규 피처
1. 더보기 버튼 클릭 시 나타나는 바텀시트가 동일하여 `useMoreSheet` 훅으로 분리했습니다.
2. 신고 및 차단 기능은 api가 나오지 않아 퍼블리싱만 진행했습니다.
=> Refactoring : QA 적용

src/app/(main)/grouping/[groupId]/components/GroupDetailHeader.client.tsx, src/app/(main)/grouping/[groupId]/components/TopSection.client.tsx, src/app/(main)/grouping/[groupId]/components/articles/NoticeItem.client.tsx, src/app/(main)/grouping/[groupId]/manage/components/ApplyCard.client.tsx, src/app/(main)/grouping/hooks/useMoreSheet.tsx
=> fix: 빌드 에러 수정

src/app/(main)/grouping/[groupId]/page.tsx, src/app/(main)/grouping/[groupId]/write/components/WriteHeader.client.tsx, src/app/(main)/grouping/[groupId]/write/page.tsx, src/app/(main)/grouping/create/page.tsx, src/app/(main)/grouping/page.tsx, src/app/(main)/profile/components/ProfileDetail.client.tsx, src/app/(main)/profile/page.tsx, src/components/PageAnimation/PageAnimation.client.tsx, src/components/PageAnimation/index.ts, src/components/Tabs/Tabs.client.tsx
- 신규 피처
1. 탭 애니메이션 및 페이지 애니메이션을 구현했습니다.
아직 디자인에 맞게 애니메이션을 구현하지 않았습니다. PageAnimation 으로 조절하면 될거같습니다!
=> Feature : 탭 애니메이션 및 페이지 애니메이션 구현

next.config.js, src/app/(main)/grouping/[groupId]/articles/[articleId]/components/ArticleHeader.client.tsx, src/app/(main)/grouping/[groupId]/articles/[articleId]/components/CommentForm.tsx, src/app/(main)/grouping/[groupId]/articles/[articleId]/page.tsx, src/app/(main)/grouping/[groupId]/components/GroupDetail.client.tsx, src/app/(main)/grouping/[groupId]/components/GroupDetailHeader.client.tsx, src/app/(main)/grouping/[groupId]/members/page.tsx, src/app/(main)/grouping/[groupId]/page.tsx, src/app/(main)/grouping/[groupId]/write/components/InputForm.client.tsx, src/app/(main)/grouping/[groupId]/write/page.tsx, src/app/(main)/grouping/components/BlockDoneModal.client.tsx, src/app/(main)/grouping/components/ReportDoneModal.client.tsx, src/app/(main)/grouping/hooks/useMoreSheet.tsx, src/app/(main)/grouping/page.tsx, src/components/PageAnimation/PageAnimation.client.tsx, src/components/TextField/SearchTextField.client.tsx, src/components/TextField/TextField.client.tsx, src/components/TextField/TextFieldController.client.tsx, src/components/common/Provider/HydrationProvider.tsx
- 신규 피처
1. 댓글 입력 시 모션을 추가했습니다.
2. 헤더에서 서버의 데이터가 필요한 경우에 액션 컴포넌트로 만들어 내부에서 Suspense로 걸리게 하도록 수정했습니다.
=> Refactoring : 댓글 입력 시 모션 추가, 헤더의 액션 분리

src/hooks/useModal/useModal.tsx
- 이슈대응
- close #384 
1. Modal 페이지 이동 시 기본으로 꺼지도록 설정하였습니다. 끄지 않으려면 `isUnmountExit=false`를 넘겨주면 됩니다.
=> Fix : QA 7차 반영

src/app/(main)/grouping/[groupId]/components/TopSection.client.tsx, src/app/(main)/grouping/components/ArticleItem.client.tsx, src/components/Modal/ImageModal.client.tsx, src/components/Modal/ModalWrapper.client.tsx, src/components/Modal/index.ts
- 신규 피처
1. 이미지 클릭 시 전체화면으로 볼 수 있게 구현했습니다. 양옆 드래그 시 다음 이미지를 확인할 수 있습니다.
=> Feature : ImageModal 구현

src/components/Modal/ImageModal.client.tsx, src/components/Modal/ModalWrapper.client.tsx
- 신규 피처
1. useState를 사용하는 분명한 클라이언트 컴포넌트에서 use client를 작성하지 않아 build 에러가 발생하여 수정하였습니다.
=> Hotfix : use client 추가

src/app/(main)/profile/components/ProfileDetailSection.client.tsx, src/app/(main)/profile/verify/components/VerifyHeader.client.tsx, src/app/(main)/profile/verify/page.tsx
- 이슈 대응
- close #409 
1. 재학생 인증 페이지로 라우팅 되지 않는 이슈를 해결하였습니다.
=> QA : 라우팅 이슈

src/apis/config/privateApi.ts, src/apis/profile/mutations.ts, src/app/(main)/profile/mates/components/MatesDeleteModal.client.tsx, src/components/Calendar/Calendar.tsx, src/components/Provider/QueryProviderWrapModal.client.tsx, src/constants/errorCode.ts
- 이슈 대응
- close #412 
1. 회원가입 후 프로필에서 재학생인증을 클릭했을 때 ‘오류가 발생합니다’ 페이지 뜸
2. 모임 개설시 캘린더 다른 날짜 체크했을 때 당일 날짜로 다시 선택 불가
=> Fix : QA 11차 반영

src/app/[lng]/(main)/grouping/components/GroupingHeader.tsx, src/app/[lng]/(main)/grouping/create/components/CreateHeader.client.tsx, src/app/[lng]/(main)/grouping/create/components/CreateModal.client.tsx, src/app/[lng]/(main)/grouping/create/components/LocationBottomSheet.client.tsx, src/app/[lng]/(main)/grouping/create/funnels/main/InputSection.client.tsx, src/app/[lng]/(main)/grouping/create/funnels/main/MainStep.client.tsx, src/app/[lng]/(main)/grouping/create/funnels/main/SettingSection.client.tsx, src/app/[lng]/(main)/grouping/create/funnels/meetDate/CalendarSection.client.tsx, src/app/[lng]/(main)/grouping/create/funnels/meetDate/MeetDateStep.client.tsx, src/app/[lng]/(main)/grouping/create/funnels/meetDate/TimeSection.client.tsx, src/app/[lng]/(main)/grouping/page.tsx, src/app/[lng]/layout.tsx, src/app/i18n/client.ts, src/app/i18n/index.ts, src/app/i18n/locales/en/grouping.json, src/app/i18n/locales/ko/grouping.json, src/app/i18n/settings.ts, src/components/Calendar/Calendar.client.tsx, src/components/Calendar/index.ts, src/utils/cookieController.ts
- 신규 피처
- close #428 
1. 모임 개설 페이지에 다국어 추가했습니다.
=> feat: 모임 개설 페이지 다국어 추가

src/app/[lng]/(main)/meeting/scrap/page.tsx, src/app/[lng]/(sub)/login/Login.tsx, src/app/[lng]/not-found.tsx
- 신규 피처
1. build 에러를 해결하였습니다.
2. login페이지 접속 시 client side에러가 발생하였습니다. 토큰 세팅이 비동기로 이루어져서 발생하는 오류인 듯하여 async-await를 추가하여 동기적으로 처리할 수 있도록 구현하였습니다.
=> Hotfix : build 에러

src/app/[lng]/(main)/meeting/participate/feedback/[groupId]/funnels/step1/Step1.tsx, src/app/[lng]/(main)/meeting/participate/feedback/[groupId]/funnels/step3/Step3.tsx, src/app/[lng]/(main)/profile/mates/components/MatesHeader.tsx, src/app/[lng]/(main)/profile/praise/components/PraiseHeader.tsx, src/app/[lng]/layout.tsx, src/app/i18n/locales/en/meeting.json, src/app/i18n/locales/ko/meeting.json, src/middleware.ts
- 신규 피처
- close #426 
1. 나의 모임 번역 보완하였습니다.
2. 내일 부스 운영 기간 동안 운영을 위해 기본 언어를 영어로 설정하였습니다.
=> Translate : 나의 모임 번역 보완

src/app/[lng]/(main)/grouping/[groupId]/components/detail/LocationSection.client.tsx, src/app/[lng]/(main)/meeting/participate/feedback/util.ts, src/app/[lng]/(sub)/join/funnels/step2/components/AgreeBottomSheet.client.tsx, src/components/Card/GroupingCard.client.tsx, src/hooks/usePlaceDetails.tsx
- 신규 피처
- close #407
1. place id로 모임장소의 이름 및 주소를 가져오도록 변경했습니다.
=> Feature : place id로 모임장소의 이름 및 주소를 가져오도록 변경

src/app/[lng]/(main)/profile/components/ProfileDetailSection.client.tsx, src/app/[lng]/(main)/profile/setting/edit/components/step1/Step1InputForm.client.tsx, src/app/[lng]/(main)/profile/setting/edit/components/step2/Step2InputForm.client.tsx, src/app/[lng]/(sub)/join/funnels/step5/components/InputForm.client.tsx, src/components/Card/GroupingCard.client.tsx
=> Feature : 이모지 추가

src/app/[lng]/(main)/grouping/components/GroupingCardList.client.tsx, src/app/[lng]/(main)/profile/setting/components/LinkSection.server.tsx, src/app/[lng]/(main)/profile/setting/delete/components/DeleteCompleteModal.client.tsx, src/app/[lng]/(main)/profile/setting/delete/components/DeleteModal.client.tsx, src/app/[lng]/(main)/profile/setting/delete/components/Step1.tsx, src/app/[lng]/(main)/profile/setting/delete/components/Step2.tsx, src/app/[lng]/(main)/profile/setting/langauge/components/Language.tsx, src/app/[lng]/(main)/profile/setting/langauge/components/LanguageHeader.tsx, src/app/[lng]/(main)/profile/setting/langauge/page.tsx, src/app/i18n/client.ts, src/app/i18n/locales/en/profile.json, src/app/i18n/locales/ko/profile.json, src/app/i18n/settings.ts, src/middleware.ts
- 신규 피처
- close #448 
1. 언어 변경을 구현하였습니다.
언어를 변경하고, 일부 페이지는 해당 언어로 변경이 바로 되지 않고, 시간이 조금 지나서 변경이 되는 이슈가 있습니다. 
SSG가 원인이라 생각하는데, 해결 방법을 함께 논의해보면 좋겠습니다.
곧 appstore 심사에 올리는 만큼, 해당 부분이 고쳐지면 머지해야 할 것 같습니다.
+ 변경된 디자인 적용하였습니다.
+ 쿠키 변경 후 강제 새로고침을 하니 위 문제가 해결되었습니다. 확인 부탁해용
=> [Feature] 언어 변경

src/app/[lng]/(main)/grouping/[groupId]/components/detail/LocationSection.client.tsx, src/app/[lng]/(main)/grouping/[groupId]/manage/components/ApplyCard.client.tsx, src/app/[lng]/(main)/meeting/participate/feedback/[groupId]/funnels/step1/Step1.tsx, src/app/[lng]/(main)/meeting/participate/feedback/[groupId]/funnels/step2/Step2.tsx, src/app/[lng]/(main)/meeting/participate/feedback/[groupId]/funnels/step3/Step3.tsx, src/app/[lng]/(main)/meeting/participate/feedback/constants.ts, src/app/[lng]/(main)/meeting/participate/feedback/util.ts, src/app/[lng]/(main)/profile/mates/components/MatesHeader.client.tsx, src/app/[lng]/(main)/profile/mates/page.tsx, src/app/[lng]/(main)/profile/praise/components/PraiseHeader.client.tsx, src/app/[lng]/(main)/profile/praise/page.tsx, src/app/[lng]/(main)/profile/setting/components/SettingHeader.client.tsx, src/app/[lng]/(main)/profile/setting/edit/components/step1/Step1.client.tsx, src/app/[lng]/(main)/profile/setting/edit/components/step1/Step1Header.client.tsx, src/app/[lng]/(main)/profile/setting/page.tsx, src/app/i18n/locales/en/common.json, src/app/i18n/locales/en/meeting.json, src/app/i18n/locales/ko/common.json
- 이슈대응
- close #450 
1. 모임 평가하기 - 1) 성격 체크 2) Best Partner 3)후기 각 하단에 버튼 텍스트 ‘다음’, ‘확인’,’완료’ 각각 영문 변환 필요
2. 프로필 수정 시 성별(한글 기준) 남성/female로 표시되어 있음.
3. 신규 지원시 호스트 기준 지원서 관리 페이지에서 오류 발생
4. 영어 버전에서 '나의 모임' 내 '승인대기모임'의 텍스트 'There are no groups pending approval yet.'을 'No groups pending approval yet.'으로 수정 요청
5. 모임 상세정보 내에서 지도 클릭시 구글맵으로 이동 기능 추가
=> Fix : 배포 전 마지막 이슈 해결

src/app/[lng]/(main)/profile/setting/information/components/Information.tsx
- 이슈대응
1. information 경로가 잘못되어 있어 수정했습니다.
=> Fix : information 경로 수정

src/app/[lng]/page.tsx
- 이슈대응
1. 배포에러 - 빠진 괄호 추가하였습니다.
=> Hotix : 배포 에러

src/middleware.ts
- 이슈대응
1. 루트 페이지에서 middleware에 의해 자동으로 쿠키가 설정되어 이 코드를 제거하였습니다.
=> Hotfix : middleware에서 쿠키 설정 제거

src/apis/profile/apis.ts, src/apis/profile/mutations.ts, src/app/[lng]/(main)/grouping/[groupId]/components/articles/NoticeItem.client.tsx, src/app/[lng]/(main)/profile/setting/delete/components/DeleteModal.client.tsx, src/app/[lng]/page.tsx
- 신규 피처
1. 회원탈퇴 api를 구현하였습니다.
- 현재, 모임이 있는 경우 에러가 발생합니다. 이 때 서버로부터 한글 메시지가 와서, 앱 심사에 지장이 있을 까봐 toast처리를 따로 안했습니다. 
- 그래서, 앱 통과 전까지는 우선 토큰 제거 후 온보딩 화면으로 redirect하는 방식으로 하면 좋을 거 같습니다.
2. 앱 내 디버깅 코드 (alert)를 제거하였습니다.
=> Feature : 회원탈퇴 api

src/app/[lng]/(sub)/join/page.tsx, src/app/[lng]/page.tsx
- 이슈대응
1. 언어 RN으로부터 받은 후 라우팅 로직을 추가하였습니다.
=> Hotfix : 언어 RN으로부터 받은 후 라우팅

src/app/[lng]/page.tsx
- 이슈대응
1. 라우팅이 되지 않아, 라우팅 위치를 수정하였습니다.
=> Hotfix : 라우팅 위치 수정

src/app/[lng]/page.tsx
- 이슈대응
1. 앱으로 실행 시 `Client-side Exception Occurred`에러가 발생하여 해당 언어로 바로 라우팅하였습니다.
=> Hotfix : 라우팅 이슈

src/middleware.ts
- 신규 피처
- close #472 
1. 이용 약관 로그인 없이 접속할 수 있습니다.
=> [Feature] 이용 약관 로그인 없이 접속

src/app/[lng]/(sub)/join/funnels/step1/components/NumberForm.client.tsx, src/app/[lng]/page.tsx, src/utils/auth/tokenController.ts
- 신규 피처
1. 기존 코드에서 `JSON.parse`, `i18n.changeLanguage` 등 비동기 함수를 `document.addEventLisnter`에 추가하여 발생한 에러라 판단하였습니다. navigator.language로 현재 디바이스의 언어를 구분하는 로직을 추가하여, 휴대폰 기기 > Safari와 Chrome 브라우저에서는 언어를 잘 구분하는 것을 확인하였습니다.
=> Refactor : 디바이스 언어 설정에 따른 언어 구분

src/app/[lng]/(main)/profile/verify/page.tsx, src/app/[lng]/(sub)/join/funnels/step3/components/EmailForm.client.tsx
- 신규 피처
1. phone 12 숫자 안눌림 -> inputMode를 추가했는데, 테스트해봐야할 것 같습니다.
2. 이메일 인증 번호 입력 창이 늦게 부팅됨
=> [Fix] 마지막 이슈들 해결

src/app/[lng]/(sub)/join/funnels/step1/components/NumberForm.client.tsx, src/app/[lng]/globals.css
- 이슈대응
- #480
1. global.css의 user-select로 인해 키보드 안쳐지는 이슈를 해결하였습니다.
=> Fix : 키보드 안쳐지는 이슈 해결

src/app/[lng]/(main)/profile/setting/langauge/components/Language.tsx, src/app/[lng]/(sub)/join/funnels/step1/components/NumberForm.client.tsx
- 신규 피처
- #480 
1. 인증번호 오지 않아도 인증번호 창 우선 뜨도록
2. 언어 바꾸지 않으면 언어 변경 버튼 비활성화
=> Feature : 자잘한 이슈 해결

src/app/[lng]/(main)/meeting/scrap/components/MeetingScrapHeader.tsx, src/app/[lng]/(main)/profile/setting/langauge/components/Language.tsx, src/components/Footer/Footer.server.tsx, src/hooks/useAppRouter.ts
- 신규 피처
1. Footer에서 페이지 이동 시 스택 안쌓이게
2. 찜한모임 참여모임 router수정
3. 페이지가 두번로딩됨(모임 상세 페이지 들어갈때)
위의 이슈들을 해결하였습니다.
=> Feature : RN 이슈해결

src/app/[lng]/(main)/community/components/ArticleItem.client.tsx, src/constants/dummyData.ts
- 신규 피처
1. community 글에 이미지 없을 때의 UI를 추가했습니다.
=> Refactoring : community 글에 이미지 없을 때의 UI 추가

src/app/[lng]/(main)/grouping/create/funnels/meetDate/TimeSection.client.tsx, src/app/[lng]/(sub)/join/funnels/step1/components/NumberVerifyForm.client.tsx, src/hooks/useCheckUpdate.ts, src/utils/getMobileDevice.ts
- 이슈대응
- close #502 
1. 서버에서 렌더링될 떄 window가 없어 발생하는 Type 에러를 해결하였습니다.
3. 키보드가 숫자 창으로 안열리는 이슈가 있었습니다. input의 type을 `tel`로 수정하였습니다.
- [참고](https://whales.tistory.com/147)
=> Fix : 이슈 해결

next.config.js
참고 : https://vercel.com/blog/how-we-optimized-package-imports-in-next-js
=> feat : optimizePackageImports옵션 추가

src/app/[lng]/(main)/grouping/create/funnels/main/MainStep.client.tsx, src/app/[lng]/(sub)/join/funnels/step4/components/InputForm.client.tsx
- 신규 피처
1. 이미지 업로드 필요한 경우, RN에 권한 요청 메시지 전달합니다.
=> Feature : 이미지 업로드 필요한 경우 RN에 권한 요청 메시지 전달

.github/CODEOWNERS
- 신규 피처
1. CODEOWNERS에 @dev-dong-su 추가, @kangju2000 를 제거합니다.
=> Setting : CODEOWNERS 변경

src/app/[lng]/(main)/grouping/create/funnels/main/MainStep.client.tsx, src/hooks/useBrowser.ts
- 신규 피처
1. 기존 날짜 객체의 시간을 설정할 때, PM의 경우 12를 더해주는데, 이 때 PM 12시의 경우 24시가 되어, new Date객체에서 에러가 발생하여 이를 수정하였습니다.
2. useBrowser가 정상적으로 Safari와 Chrome을 구분하지 못하여 이를 해결하였습니다.
=> Hotfix: 날짜 에러 해결

src/apis/profile/type.ts, src/app/[lng]/(main)/profile/components/ProfileDetailSection.client.tsx, src/app/[lng]/(main)/profile/setting/edit/components/step1/Step1InputForm.client.tsx, src/app/[lng]/(sub)/join/funnels/step4/components/InputForm.client.tsx, src/constants/dummyData.ts
- 이슈 대응
1. 기존 오타 MAILE, FEMAIL을 서버 스펙에 맞춰 MALE, FEMALE로 변경합니다.
2.
3.
=> HOTFIX: MAILE, FEMAIL -> MALE, FEMALE 오타 수정

src/app/[lng]/(main)/profile/setting/edit/components/step1/CountryBotoomSheet.tsx, src/constants/countary.json
- 신규 피처
1. 누락된 대만 국가를 추가합니다.
2.
3.
opendata에서 대만 국가 국기가 빈 이미지로 나와서 s3버킷에 업로드하고 해당 이미지로 대체 해서 추가했습니다.
=> Hotfix: 누락된 국가 추가

src/apis/groups/apis.ts, src/apis/groups/type.ts, src/app/[lng]/(main)/community/[articleId]/components/ArticleDetail.tsx, src/app/[lng]/(main)/community/[articleId]/components/CommentList.tsx, src/app/[lng]/(main)/grouping/[groupId]/articles/[articleId]/components/ArticleDetail.client.tsx
- 이슈 대응
1. 커뮤니티 페이지를 만드는 과정에서 기존 CommentList컴포넌트를 재활용했는데, 이 과정에서 DummyData를 공통적으로 불러왔습니다. 그래서 기존 CommentList를 사용하던 게시판에까지 사이드이펙트를 끼쳐서, 이를 해결했습니다.
=> HotFix: 기존 커뮤니티에서는 실제 데이터 사용

src/app/[lng]/(main)/community/[articleId]/components/CommentForm.tsx
- 신규 피처
- #596 
Comment 좋아요 우측의 대댓글 버튼을 누르면 CommentForm에 Focus가 되어 바로 입력을 할 수 있도록 수정했습니다.
=> Feature: 대댓글 입력시 CommentForm에 Focus가 되도록 수정

src/apis/common/apis.ts, src/app/[lng]/(main)/grouping/create/components/CreateGroupContext.tsx, src/app/[lng]/(main)/grouping/create/funnels/main/UploadSection.client.tsx
- 이슈 대응
1. 안드로이드 기기에서 이미지 압축이 정상적으로 동작하지 않는 이슈를 해결했습니다.
=> Hotfix : 이미지 업로드 이슈 해결

src/apis/auth/mutations.ts, src/apis/config/privateApi.ts, src/app/[lng]/(main)/profile/setting/delete/components/DeleteModal.client.tsx, src/app/[lng]/(main)/profile/setting/edit/components/step1/Step1InputForm.client.tsx, src/app/[lng]/(sub)/join/funnels/step1/components/NumberForm.client.tsx, src/app/[lng]/(sub)/join/funnels/step1/components/NumberVerifyForm.client.tsx, src/app/[lng]/page.tsx, src/app/[lng]/template.tsx, src/components/Error/BaseError.tsx, src/hooks/token/useLogin.ts, src/hooks/token/useLogout.ts, src/hooks/useListenMessageToReactNative.ts, src/hooks/useSentry.ts
- 신규 피처
- close #602
1. RN에 메시지 전송, 수신 모듈화 하였습니다. (`useListenMessageToReactNative`)
2. 로그인과 로그아웃을 커스텀 훅으로 분리하였습니다. (`useLogin`, `useLogout`)
=> Feature : 로그인, 로그아웃 모듈화

.github/workflows/ci.yml, packages/app/ios/Podfile.lock, packages/app/src/components/OnBoarding.tsx, packages/app/src/components/WebViewContainer.tsx, packages/web/src/apis/config/privateApi.ts, packages/web/src/hooks/token/useLogin.ts, packages/web/src/hooks/token/useLogout.ts, packages/web/src/hooks/useListenMessageToReactNative.ts, packages/web/src/middleware.ts, packages/web/src/utils/auth/tokenController.ts
- 이슈 대응
- #618 
RN에 토큰 저장을 위한 로직을 제거했습니다.
토큰은 모두 web어플리케이션의 쿠키에서 관리합니다.
다음 문서에 관련한 사이드 이펙트를 정리했습니다!
[관련 문서](https://noisy-sulfur-8e8.notion.site/RN-Webview-StackNavigation-Token-d964e23b5cd84af9a36d12680431cf44?pvs=4)
=> Fix: RN 토큰 저장 로직 제거

packages/app/ios/Podfile.lock, packages/app/src/components/OnBoarding.tsx, packages/app/src/components/WebViewContainer.tsx, packages/web/src/app/[lng]/(main)/community/page.tsx, packages/web/src/app/[lng]/(main)/grouping/[groupId]/manage/page.tsx, packages/web/src/app/[lng]/(main)/grouping/page.tsx, packages/web/src/app/[lng]/(main)/meeting/participate/page.tsx, packages/web/src/app/[lng]/(main)/meeting/scrap/page.tsx, packages/web/src/app/[lng]/(main)/profile/page.tsx, packages/web/src/app/[lng]/not-found.tsx, packages/web/src/components/Footer/Footer.tsx, packages/web/src/hooks/useAppRouter.ts
- 신규 피처
- close #621 
1. 쿠키 이슈로 인해 기존 TabBar, Stack을 제거하였습니다. 지금까지 작업 사항 운영 서버에 배포 후, 쿠키 이슈를 해결하여 다시 추가하는 방안으로 해결하고자 합니다.
=> Chore : 기존 TabBar, Stack 제거

packages/app/src/components/OnBoarding.tsx, packages/web/src/apis/auth/mutations.ts
- 이슈 대응
- closing #636 
1. 토큰 설정하는 로직이 추가되어 에러가 발생했습니다. 이를 제거하였습니다.
=> Fix : 로그인 에러 해결

.gitignore, packages/web/package.json, packages/web/src/apis/groups/mutations.tsx, packages/web/src/app/[lng]/(main)/community/components/ContentSection.tsx, packages/web/src/app/[lng]/(main)/grouping/[groupId]/manage/components/ManageDetail.client.tsx, packages/web/src/app/[lng]/(main)/grouping/create/components/LocationBottomSheet.client.tsx, packages/web/src/app/[lng]/(main)/grouping/create/funnels/main/UploadSection.client.tsx, packages/web/src/app/[lng]/(main)/profile/components/ProfileDetailSection.client.tsx, packages/web/src/components/Animation/ButtonAnimation.tsx, packages/web/src/components/Calendar/Calendar.client.tsx, packages/web/src/components/Card/GroupingCard.client.tsx, packages/web/src/components/Modal/ImageModal.client.tsx, packages/web/src/components/Modal/ModalWrapper.client.tsx, packages/web/src/components/Modal/Toast.client.tsx, packages/web/src/components/Motion/Motion.tsx, packages/web/src/components/Motion/index.ts, packages/web/src/components/Tabs/Tabs.tsx, packages/web/src/hooks/useModal/useModal.tsx, yarn.lock
- 리팩토링
- #665 
bundle 사이즈가 큰 framer motion의 최적화를 위해 공식문서를 참고해 
Motion 컴포넌트를 작성했습니다.
63d97cac4af3314ea3734756bd482693fb7abe0f
큰 이미지의 경우 업로드 시간이 오래 걸리는 경우가 있어 Loading 컴포넌트를 노출할 수 있도록 변경했습니다.
업로드가 끝나고 이미지를 보여줄 때 걸리는 시간도 최소화 하기 위해 base64로 인코딩된 previewimage를 렌더링 합니다.
33ea57e14b36c451537179cd5589677f0bc26863
같은 기능을 하면서 번들 사이즈가 90% 작은 react-glider로 변경했습니다. 
9eee4af2c7447605ec8b2ca2630a0e1a2cff11e0
43ca556b45b692f8e6433049d56099e3b805ba6e
6a591a3c5338bdb217b601803ee9958d7e0b61d4
=> Refactor: bundle, routing param 누락 추가

.gitignore, packages/web/package.json, packages/web/src/apis/groups/mutations.tsx, packages/web/src/app/[lng]/(main)/community/components/ContentSection.tsx, packages/web/src/app/[lng]/(main)/grouping/[groupId]/manage/components/ManageDetail.client.tsx, packages/web/src/app/[lng]/(main)/grouping/create/components/LocationBottomSheet.client.tsx, packages/web/src/app/[lng]/(main)/grouping/create/funnels/main/UploadSection.client.tsx, packages/web/src/app/[lng]/(main)/profile/components/ProfileDetailSection.client.tsx, packages/web/src/components/Animation/ButtonAnimation.tsx, packages/web/src/components/Calendar/Calendar.client.tsx, packages/web/src/components/Card/GroupingCard.client.tsx, packages/web/src/components/Modal/ImageModal.client.tsx, packages/web/src/components/Modal/ModalWrapper.client.tsx, packages/web/src/components/Modal/Toast.client.tsx, packages/web/src/components/Motion/Motion.tsx, packages/web/src/components/Motion/index.ts, packages/web/src/components/Tabs/Tabs.tsx, packages/web/src/hooks/useModal/useModal.tsx, yarn.lock
* refactor: framer-motion lazy load
* refactor: group detail page url 수정
* refactor: group 생성 페이지 이미지 업로드 시 Loading 노출
* refactor: swiper -> react-glider로 변경
* refactor: groupdetail page param 누락 수정
- 신규 피처
1.
2.
3.
=> Release v1.4.8
